export { default as Stadium } from "../../assets/stadium-gca63d4ee5_1920.jpg";
export { default as Homepage } from "../../assets/pexels-philipp-birmes-830891.jpg";
export { default as Tunnel } from "../../assets/tunnel-g8cb275ef8_1920.jpg";
export { default as Road } from "../../assets/pexels-joshua-welch-1624600.jpg";
export { default as Bridge } from "../../assets/bridge-g05353173d_1920.jpg";
export { default as Building } from "../../assets/pexels-pixabay-290275.jpg";
export { default as Hydro } from "../../assets/pexels-mark-plötz-1821979.jpg";
export { default as RawMaterials } from "../../assets/pexels-tom-fisk-2101137.jpg";
export { default as Airports } from "../../assets/night-flight-g3ffaff48f_1920.jpg";
